application: hs-prorogue
version: 1
runtime: python
api_version: 1

handlers:
- url: /style
  static_dir: static/style

- url: /script
  static_dir: static/style

- url: /image
  static_dir: static/style

- url: /favicon.ico
  static_files: static/image/favicon.ico
  upload: static/image/favicon.ico

- url: /.*
  script: main.py
